### ISSUE TITLE
Импорт данных в БД проекта

### ISSUE THREAD

**Issue by Scorpiortem** [Scorpiortem/4.2-1#1]
Диан, база данных создана, можешь приступать к импорту значений из CSV файла в БД проекта

**Comment by MishinaDiana** [comment]
Сделано. Надеюсь, всё хорошо.

**Comment by Scorpiortem** [comment]
Я посмотрел и почему-то у меня на компьютере скрипт импорта не работает... Буду проверять, возможно ошибка с моей стороны. Но ты на всякий случай тоже проверь

**Comment by MishinaDiana** [comment]
Да, хорошо. Наверное, стоит сам файл повнимательнее изучить, и учесть все отклонения.

**Comment by Scorpiortem** [comment]
Хорошо, Диан, пока разбирайся. Я ставлю дедлайн до 23.12. По идее должно хватить времени

**Comment by Scorpiortem** [comment]
Диан, скрипт БД поменял, можно приступать к импорту данных. Ты же уже изменила свой старый скрипт импорта?

**Comment by Scorpiortem** [comment]
Диан, дедлайн тебе смещаю до 25 числа из-за подготовки к зачёту + неожиданных ошибок с БД. Ближе к дедлайну подключусь к решению ошибки, возможно, она с моей стороны

**Comment by Scorpiortem** [comment]
Ну в общем зачёл как решённое, потому что новый скрипт теперь корректно работает

**Comment by MishinaDiana** [comment]
Хорошо, спасибо
