### ISSUE TITLE
Создание ER-диаграммы

### ISSUE THREAD

**Issue by Scorpiortem** [Scorpiortem/4.2-1#2]
Антон, база данных создана, можешь начать делать ER-диаграмму

**Comment by antonkhokhlow** [comment]
Выложил ER-диаграмму, проверь

**Comment by Scorpiortem** [comment]
Проверил, отметил как выполненное

**Comment by Scorpiortem** [comment]
Антон, напоминаю, что ещё нужно заняться нормализацией данных и docker. Дедлайн ставлю до 23.12. Ну край до 24.12. Мне кажется недели активной работы должно хватить на это

**Comment by antonkhokhlow** [comment]
Понял, уже работаю над этим.

**Comment by antonkhokhlow** [comment]
При работе с docker выдаёт ошибку "no configuration file provided: not found".
Пока не знаю как исправить.

**Comment by Scorpiortem** [comment]
Хорошо, давай попробуем разобраться вместе, я же как никак тимлид, могу помочь, чем смогу. Заходи в discord, расскажешь подробнее о своей проблеме

**Comment by antonkhokhlow** [comment]
Создал  ER-диаграмму, а также загрузил модель базы данных, нормализовал данные

**Comment by Scorpiortem** [comment]
Принял, зачёл как выполненное

**Comment by Scorpiortem** [comment]
Антон, напоминаю, у нас дедлайн завтра. Что там с docker'ом? Исправил ошибки, которые возникли?

**Comment by antonkhokhlow** [comment]
Да, докер готов

**Comment by antonkhokhlow** [comment]
Жду изменений БД и окончательный iNSERT, тогда выложу конечную версию.

**Comment by antonkhokhlow** [comment]
Получил окончательный insert приступаю к загрузке docker

**Comment by antonkhokhlow** [comment]
docker отказывается работать, попробую сделать другим способом

**Comment by antonkhokhlow** [comment]
Загрузил docker, работает корректно

**Comment by Scorpiortem** [comment]
Отлично, работу засчитываю
