### ISSUE TITLE
Развёрстка на db4.net

### ISSUE THREAD

**Issue by Scorpiortem** [Scorpiortem/4.2-1#3]
Глеб, база данных создана, можешь начать приступать к развёрстке

**Comment by godleifrg** [comment]
Сегодня изучал теорию
Завтра сделаю, надеюсь все пройдет без проблем

**Comment by godleifrg** [comment]
![image](https://github.com/Scorpiortem/4.2-1/assets/147144797/bbd02bad-9644-4b39-bd7c-350b48aa3f6e)
Вообщем
Я зарегал бд
Но я не могу залить скрипт и csv на сервер, выдает вот такую тему
Попробовал передать все привилегии, но точно такая же ошибка
Завтра еще подумаю и посмотрю

**Comment by Scorpiortem** [comment]
Честно говоря, я пока сам не смотрел ничего на эту тему :) Так что с этим пока что никак не помогу. Но, как буду посвободнее, тоже гляну, может смогу помочь. А пока что поищи информацию в интернете сам, возможно у кого-то были похожие ошибки

**Comment by Scorpiortem** [comment]
Хорошо, Глеб. В общем, не откладывай на потом. Я дедлайн ставлю до 23.12. Было бы славно, если бы получилось приложить все свои усилия и мы все вместе успели сделать проект до его сдачи :)

**Comment by Scorpiortem** [comment]
Глеб, скрипт БД поменял, если у тебя уже всё починено на db4.net, то можешь приступать к завершению своей работы, так как наша БД, с очень высоким шансом, меняться больше не будет, по крайней мере не хотелось бы...)

**Comment by Scorpiortem** [comment]
Глеб, напоминаю, дедлайн у нас стоит 23.12 по твоему заданию, попытайся загрузить ту БД, которая есть у нас сейчас до завтрашнего вечера, у Дианы в импорте возникли непредсказуемые ошибки, возможно тут виноват я и БД не совсем верно сконструирована(ошибки в типах данных и т.п). Поэтому прошу, загрузи пока то, что есть, а потом, как решим ошибку, заменим. Нам нужно хотя бы понять, загрузится она на сервак или нет

**Comment by godleifrg** [comment]
Да, уже приступил к этой работе край завтра утром выгружу и дам обратную связь
